// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM_e678QSZpAhzbRb33JnUvvuhkSEGVOg',
    appId: '1:107250000063:web:93948274a342fadf4a660a',
    messagingSenderId: '107250000063',
    projectId: 'flutterlocalauthtutorial',
    authDomain: 'flutterlocalauthtutorial.firebaseapp.com',
    storageBucket: 'flutterlocalauthtutorial.firebasestorage.app',
    measurementId: 'G-XCQJ2MKVG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlT3YQbBAI2KnuYhd_uEloX9v52tq7bJU',
    appId: '1:107250000063:android:c4337db506a078a84a660a',
    messagingSenderId: '107250000063',
    projectId: 'flutterlocalauthtutorial',
    storageBucket: 'flutterlocalauthtutorial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDLCjEvgplL_tg_yfEbe2Y8PAVXErovBk',
    appId: '1:107250000063:ios:4482510374fc27b34a660a',
    messagingSenderId: '107250000063',
    projectId: 'flutterlocalauthtutorial',
    storageBucket: 'flutterlocalauthtutorial.firebasestorage.app',
    iosBundleId: 'com.yt.flutterLocalAuthTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDLCjEvgplL_tg_yfEbe2Y8PAVXErovBk',
    appId: '1:107250000063:ios:4482510374fc27b34a660a',
    messagingSenderId: '107250000063',
    projectId: 'flutterlocalauthtutorial',
    storageBucket: 'flutterlocalauthtutorial.firebasestorage.app',
    iosBundleId: 'com.yt.flutterLocalAuthTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM_e678QSZpAhzbRb33JnUvvuhkSEGVOg',
    appId: '1:107250000063:web:9995f7565d681be44a660a',
    messagingSenderId: '107250000063',
    projectId: 'flutterlocalauthtutorial',
    authDomain: 'flutterlocalauthtutorial.firebaseapp.com',
    storageBucket: 'flutterlocalauthtutorial.firebasestorage.app',
    measurementId: 'G-VK8L702TFY',
  );
}
